name: flutterwork
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  noise_meter: ^5.0.2
  provider: ^6.1.2
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.0.1

flutter_native_splash:
  color: "#F2F2F2"
  image: assets/images/splash_logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png